from django.conf.urls import patterns, url

# This should contain urls related to registry ONLY
urlpatterns = patterns('cpovc_forms.views',
                       url(r'^$', 'forms_home', name='forms'),
                       url(r'^forms_registry/$', 'forms_registry',
                           name='forms_registry'),
                       url(r'^documents_manager/$', 'documents_manager',
                           name='documents_manager'),
                       url(r'^documents_manager_search/$', 'documents_manager_search',
                           name='documents_manager_search'),
                       url(r'^case_record_sheet/(?P<id>\d+)/$', 'case_record_sheet',
                           name='case_record_sheet'),
                       url(r'^view_case_record_sheet/(?P<id>\w+)/$', 'view_case_record_sheet',
                           name='view_case_record_sheet'),
                       url(r'^edit_case_record_sheet/(?P<id>\w+)/$', 'edit_case_record_sheet',
                           name='edit_case_record_sheet'),
                       url(r'^delete_case_record_sheet/(?P<id>\w+)/$', 'delete_case_record_sheet',
                           name='delete_case_record_sheet'),
                       url(r'^case_events/(?P<id>\w+)/$', 'case_events',
                           name='case_events'),
                       url(r'^ovc_search/$', 'ovc_search', name='ovc_search'),
                       url(r'^save_encounter/$', 'save_encounter',
                           name='save_encounter'),
                       url(r'^view_encounter/$', 'view_encounter',
                           name='view_encounter'),
                       url(r'^edit_encounter/$', 'edit_encounter',
                           name='edit_encounter'),
                       url(r'^delete_encounter/$', 'delete_encounter',
                           name='delete_encounter'),
                       url(r'^save_court/$', 'save_court', name='save_court'),
                       url(r'^view_court/$', 'view_court',
                           name='view_court'),
                       url(r'^edit_court/$', 'edit_court',
                           name='edit_court'),
                       url(r'^delete_court/$', 'delete_court',
                           name='delete_court'),
                       url(r'^save_placement/$', 'save_placement',
                           name='save_placement'),
                       url(r'^view_placement/$', 'view_placement',
                           name='view_placement'),
                       url(r'^edit_placement/$', 'edit_placement',
                           name='edit_placement'),
                       url(r'^delete_placement/$', 'delete_placement',
                           name='delete_placement'),
                       url(r'^manage_refferal/$', 'manage_refferal',
                           name='manage_refferal'),
                       url(r'^manage_refferal001/$', 'manage_refferal001',
                           name='manage_refferal001'),
                       url(r'^manage_refferal002/$', 'manage_refferal002',
                           name='manage_refferal002'),
                       url(r'^manage_refferal003/$', 'manage_refferal003',
                           name='manage_refferal003'),
                       url(r'^getJsonObject001/$', 'getJsonObject001',
                           name='getJsonObject001'),
                       url(r'^close_case/$', 'close_case', name='close_case'),)
